import Head from 'next/head';
import React, { useState, useEffect } from "react";
import styles from '../styles/Home.module.css';

import { useSelector, useDispatch } from 'react-redux';
import { getListProducts } from "../redux/action/products/creator";

import Machine from './components/machine';
import InsertCoins from './components/insertCoins';

const Home = () => { 
  const productsList = useSelector((state) => state.products.productsList)
  const dispatch = useDispatch();

  const fetchProductsList = async () => {
    dispatch(getListProducts());
  };

  useEffect(() => {
    fetchProductsList();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const [coins, setCoins] = useState(0);

  const onCoinChanged = total => {
    setCoins(total);
  };

  const onBuy = (price, id) => {
    setCoins(coins - price);
    productsList.forEach((item) => {
      if (item.id == id) item.stock = item.stock - 1;
    });
  };

  const onStockReductionData = () => {
    fetchProductsList();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Vending Machine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title + " mb-4"}>
          Welcome to Vending Machine
        </h1>

        <div className="row">
          <div className="col-sm-6 col-12">
            <Machine productsList={productsList} coins={coins} onBuy={onBuy} />
          </div>
          <div className="col-sm-6 col-12">
            <InsertCoins coins={coins} onCoinChanged={onCoinChanged} onStockReductionData={onStockReductionData} />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} Zikri Ramdani
        </a>
      </footer>
    </div>
  )
}

export default Home;
